name: Merge Queue Manager

on:
  # Allow self-dispatch to process next PR in queue
  workflow_dispatch:

  # Trigger after entry/remove workflows complete
  workflow_run:
    workflows: ["Merge Queue Entry", "Merge Queue Remove"]
    types: [completed]

# Only one PR should be processed at a time
concurrency:
  group: merge-queue-processor
  cancel-in-progress: false

jobs:
  process-queue:
    name: Process Merge Queue
    runs-on: ubuntu-latest

    steps:
      - name: Generate GitHub App token
        id: app-token
        uses: actions/create-github-app-token@v1
        with:
          app-id: ${{ vars.MERGE_QUEUE_APP_ID }}
          private-key: ${{ secrets.MERGE_QUEUE_APP_PRIVATE_KEY }}

      - name: Process next PR
        id: process
        uses: BloomAndWild/merge-queue@v1/src/actions/process-queue
        with:
          # Authentication (GitHub App installation token)
          github-token: ${{ steps.app-token.outputs.token }}

          # Repository info (auto-detected)
          repository: ${{ github.repository }}

          # Queue configuration (set the MERGE_QUEUE_LABEL repo variable to customise)
          queue-label: ${{ vars.MERGE_QUEUE_LABEL || 'ready' }}
          failed-label: merge-queue-failed
          conflict-label: merge-queue-conflict
          processing-label: merge-processing
          updating-label: merge-updating
          queued-label: queued-for-merge

          # Validation requirements
          allow-draft: false
          block-labels: do-not-merge,wip
          ignore-checks: 'Add PR to Merge Queue,Remove PR from Merge Queue,Process Merge Queue'

          # Branch update configuration
          auto-update-branch: true
          update-timeout-minutes: 30

          # Merge configuration
          merge-method: squash
          delete-branch-after-merge: true

      # Optional: Send a Slack notification when a PR is merged or fails.
      # Requires a SLACK_WEBHOOK_URL secret containing an incoming webhook URL.
      - name: Notify Slack
        if: steps.process.outputs.processed == 'true'
        uses: BloomAndWild/merge-queue@v1/src/actions/notify
        with:
          slack-webhook-url: ${{ secrets.MERGE_QUEUE_SLACK_WEBHOOK_URL }}
          github-token: ${{ steps.app-token.outputs.token }}
          repository: ${{ github.repository }}
          pr-number: ${{ steps.process.outputs.pr-number }}
          result: ${{ steps.process.outputs.result }}

      # Self-dispatch: if a PR was processed, trigger another run to process the
      # next one in the queue.
      - name: Process next in queue
        if: steps.process.outputs.processed == 'true'
        env:
          GH_TOKEN: ${{ steps.app-token.outputs.token }}
        run: gh workflow run "${{ github.workflow }}" --repo "${{ github.repository }}"
